### PR TITLE
Add Openbox theme for Arc-Darker

### PR DESCRIPTION
**Pull request by Narrat**
Similar to the existing ob-themes, but uses in some places brighter colors (menu-items background, osd unhilight background)
_____
First of all. Thanks for your work.
I decided to make some adjustments for my personal liking, because I'm using the Arc-Darker variant, and found the dark openbox theme to dark, and the normal one to inverse.
To achieve some brighter places I switched the coloring scheme (existing one used the title color and the color of the bookmarks) to title color and address-bar color.

And I just want to offer, to include my addition. Dunno if it is desired, or not (because of the change in the used coloring scheme).

Best regards

Edit: Oh, I forgot to ask. I want to know where I can get this wallpaper used in the screens

### CODE REVIEW

**Comment by dglava** [comment]
Thank you for the contribution.
I have checked it out quickly and it looks fine. I don't really use this theme and I stopped following the Arc GTK theme changes, so I can't really say if it's still sticking to the color scheme provided by the original Arc GTK theme. Either way, I'll add it and if people notice some inconsistencies, they can report them.

Here's a link to the wallpaper. You can use Google reverse image search to find it in other sizes.

https://s23.postimg.org/ss08dk74r/image.png

**Comment by Narrat** [comment]
I see. At least the color codes seem to be valid and in general each ob theme fits its Arc counterpart.
May I ask to which theme you switched?

And thanks a lot,regarding the link for the wallpaper

**Comment by dglava** [comment]
I use a more neutral one, because the Arc theme seems to be really Arc GTK specific and Arc has too much contrast for my taste. I'm using a slightly modified version of Numix (no colored highlights on the window bar and a more "dull" blue menu).

https://github.com/dglava/pkgbuilds/tree/master/numix-mod-theme/Numix-mod

**Comment by Narrat** [comment]
Dunno how I could miss the Numix theme while searching for a replacement.
Thanks for the hint.

**Pull request merged**
